using System.IO;
#if UNITY_EDITOR
using UnityEditor;
#endif
using UnityEngine;
using UnityEngine.SceneManagement;

public class LUTBeamManager : MonoBehaviour
{
    public Texture[] gobos;
    public string AutoGenerateDirectory = "Assets/LUTBeam/Autogenerated";

    public string prefix = "";

    public int LUTResolution = 1024;
    public int GoboResolution = 512;

#if UNITY_EDITOR
    [ContextMenu("Generate Texture Array")]
    public void _GenerateTextureArray()
    {
        Texture2D[] goboTextures = new Texture2D[gobos.Length];
        Texture2D[] lutTextures = new Texture2D[gobos.Length];

        Material material = new Material(Shader.Find("LUTBeam/GoboLookupGenerator"));

        for (int q = 0; q < gobos.Length; q++)
        {
            if (!(gobos[q] is Texture2D))
                continue;

            Texture2D Gobo = gobos[q] as Texture2D;

            if (!Gobo)
                return;

            RenderTexture tempRT = new RenderTexture(LUTResolution, LUTResolution, 32, RenderTextureFormat.ARGBFloat);

            material.SetTexture("_MainTex", Gobo);

            // Enable supersampling mode of the baker because it makes it look way better!
            Shader.SetGlobalFloat("_Supersample", 1);
            
            Graphics.Blit(null, tempRT, material);
            
            Shader.SetGlobalFloat("_Supersample", 0);

            RenderTexture.active = tempRT;
            Texture2D tex = new Texture2D(LUTResolution, LUTResolution, TextureFormat.RGBAFloat, false);
            tex.ReadPixels(new Rect(0, 0, LUTResolution, LUTResolution), 0, 0);
            tex.Apply();
            RenderTexture.active = null;

            // Convert linear to srgb in the texture
            for (int x = 0; x < LUTResolution; x++)
            {
                for (int y = 0; y < LUTResolution; y++)
                {
                    Color c = tex.GetPixel(x, y);
                    c.r = Mathf.LinearToGammaSpace(c.r);
                    c.g = Mathf.LinearToGammaSpace(c.g);
                    c.b = Mathf.LinearToGammaSpace(c.b);
                    tex.SetPixel(x, y, c);
                }
            }
            tex.Apply();

            goboTextures[q] = Gobo;
            lutTextures[q] = tex;
        }
        TextureFormat format = TextureFormat.BC4;

        Scene scene = SceneManager.GetActiveScene();

        if (!Directory.Exists(AutoGenerateDirectory))
            Directory.CreateDirectory(AutoGenerateDirectory);

        Texture2DArray texArray = new Texture2DArray(GoboResolution, GoboResolution, gobos.Length, format, false, false);
        Texture2DArray lutArray = new Texture2DArray(LUTResolution, LUTResolution, gobos.Length, format, false, false);

        int mip = 0;
        for (int i = 0; i < gobos.Length; i++)
        {
            RenderTexture goboTempRT = new RenderTexture(GoboResolution, GoboResolution, 0, RenderTextureFormat.ARGBFloat);
            Texture2D goboTex = new Texture2D(GoboResolution, GoboResolution, TextureFormat.RGBAFloat, false, false);
            Graphics.Blit(goboTextures[i], goboTempRT);
            goboTex.ReadPixels(new Rect(0, 0, GoboResolution, GoboResolution), 0, 0);
            goboTex.Apply(true);
            EditorUtility.CompressTexture(goboTex, format, TextureCompressionQuality.Best);
            Graphics.CopyTexture(goboTex, 0, mip, texArray, i, mip);

            RenderTexture lutTempRT = new RenderTexture(LUTResolution, LUTResolution, 0, RenderTextureFormat.ARGBFloat);
            Texture2D lutTex = new Texture2D(LUTResolution, LUTResolution, TextureFormat.RGBAFloat, false, false);
            Graphics.Blit(lutTextures[i], lutTempRT);
            lutTex.ReadPixels(new Rect(0, 0, LUTResolution, LUTResolution), 0, 0);
            lutTex.Apply(true);
            EditorUtility.CompressTexture(lutTex, format, TextureCompressionQuality.Best);
            Graphics.CopyTexture(lutTex, 0, mip, lutArray, i, mip);
        }


        string texArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} - Gobo Textures.asset";
        string lutArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} - LUT Textures.asset";
        if (!string.IsNullOrWhiteSpace(prefix))
        {
            texArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} {prefix} - Gobo Textures.asset";
            lutArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} {prefix} - LUT Textures.asset";
        }


        Texture2DArray existingTexArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(texArrayFilePath);
        if (existingTexArray)
        {
            EditorUtility.CopySerialized(texArray, existingTexArray);
            EditorUtility.SetDirty(existingTexArray);
            texArray = existingTexArray;
        }
        else
        {
            AssetDatabase.CreateAsset(texArray, texArrayFilePath);
        }

        Texture2DArray existingLutArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(lutArrayFilePath);
        if (existingLutArray)
        {
            EditorUtility.CopySerialized(lutArray, existingLutArray);
            EditorUtility.SetDirty(existingLutArray);
            lutArray = existingLutArray;
        }
        else
        {
            AssetDatabase.CreateAsset(lutArray, lutArrayFilePath);
        }

        AssetDatabase.SaveAssets();

        EditorGUIUtility.PingObject(lutArray);
    }
#endif
}