#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;

public class LUTBeamMaterialManager : MonoBehaviour
{
    public Texture[] gobos;
    public Material[] materials;
    public string AutoGenerateDirectory = "Assets/LUTBeam/Autogenerated";
    public int Resolution = 1024;

    [ContextMenu("Generate Materials")]
    public void _GenerateMaterials()
    {
        Texture2D[] goboTextures = new Texture2D[gobos.Length];
        Texture2D[] lutTextures = new Texture2D[gobos.Length];

        Material material = new Material(Shader.Find("LUTBeam/GoboLookupGenerator"));

        for (int q = 0; q < gobos.Length; q++)
        {
            if (!(gobos[q] is Texture2D))
                continue;

            Texture2D Gobo = gobos[q] as Texture2D;

            if (!Gobo)
                return;

            RenderTexture tempRT = new RenderTexture(Resolution, Resolution, 32, RenderTextureFormat.ARGBFloat);

            material.SetTexture("_MainTex", Gobo);

            Graphics.Blit(null, tempRT, material);

            RenderTexture.active = tempRT;
            Texture2D tex = new Texture2D(Resolution, Resolution, TextureFormat.RGBAFloat, false);
            tex.ReadPixels(new Rect(0, 0, Resolution, Resolution), 0, 0);
            tex.Apply();
            RenderTexture.active = null;

            // Convert linear to srgb in the texture
            for (int x = 0; x < Resolution; x++)
            {
                for (int y = 0; y < Resolution; y++)
                {
                    Color c = tex.GetPixel(x, y);
                    c.r = Mathf.LinearToGammaSpace(c.r);
                    c.g = Mathf.LinearToGammaSpace(c.g);
                    c.b = Mathf.LinearToGammaSpace(c.b);
                    tex.SetPixel(x, y, c);
                }
            }
            tex.Apply();

            goboTextures[q] = Gobo;
            lutTextures[q] = tex;
        }
        TextureFormat format = TextureFormat.RFloat;

        Texture2DArray texArray = new Texture2DArray(Resolution, Resolution, gobos.Length, format, false, false);
        Texture2DArray lutArray = new Texture2DArray(Resolution, Resolution, gobos.Length, format, false, false);

        for (int i = 0; i < gobos.Length; i++)
        {

            RenderTexture goboTempRT = new RenderTexture(Resolution, Resolution, 0, RenderTextureFormat.ARGBFloat);
            Texture2D goboTex = new Texture2D(Resolution, Resolution, TextureFormat.RGBAFloat, false, false);
            Graphics.Blit(goboTextures[i], goboTempRT);
            goboTex.ReadPixels(new Rect(0, 0, Resolution, Resolution), 0, 0);
            goboTex.Apply(true);
            
            EditorUtility.CompressTexture(goboTex, format, TextureCompressionQuality.Best);

            for (int mip = 0; mip < goboTex.mipmapCount; mip++)
            {
                Graphics.CopyTexture(goboTex, 0, mip, texArray, i, mip);
            }

            RenderTexture lutTempRT = new RenderTexture(Resolution, Resolution, 0, RenderTextureFormat.ARGBFloat);
            Texture2D lutTex = new Texture2D(Resolution, Resolution, TextureFormat.RGBAFloat, false, false);
            Graphics.Blit(lutTextures[i], lutTempRT);
            lutTex.ReadPixels(new Rect(0, 0, Resolution, Resolution), 0, 0);
            lutTex.Apply(true);
            EditorUtility.CompressTexture(lutTex, format, TextureCompressionQuality.Best);

            for (int mip = 0; mip < lutTex.mipmapCount; mip++)
            {
                Graphics.CopyTexture(lutTex, 0, mip, lutArray, i, mip);
            }
        }

        Scene scene = SceneManager.GetActiveScene();

        if (!Directory.Exists(AutoGenerateDirectory))
            Directory.CreateDirectory(AutoGenerateDirectory);

        string texArrayFilename = $"{AutoGenerateDirectory}/{scene.name} - Gobo Textures.asset";
        string lutArrayFilename = $"{AutoGenerateDirectory}/{scene.name} - LUT Textures.asset";

        Texture2DArray existingTexArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(texArrayFilename);
        if (existingTexArray != null && existingTexArray.width == texArray.width && existingTexArray.height == texArray.height && existingTexArray.depth == texArray.depth)
        {
            int mipCount = Mathf.Min(texArray.mipmapCount, existingTexArray.mipmapCount);
            for (int element = 0; element < texArray.depth; element++)
            {
                for (int mip = 0; mip < mipCount; mip++)
                {
                    Graphics.CopyTexture(texArray, element, mip, existingTexArray, element, mip);
                }
            }
            texArray = existingTexArray;
            EditorUtility.SetDirty(texArray);
        }
        else
        {
            AssetDatabase.CreateAsset(texArray, texArrayFilename);
        }

        Texture2DArray existingLutArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(lutArrayFilename);
        if (existingLutArray != null && existingLutArray.width == lutArray.width && existingLutArray.height == lutArray.height && existingLutArray.depth == lutArray.depth)
        {
            int mipCount = Mathf.Min(lutArray.mipmapCount, existingLutArray.mipmapCount);
            for (int element = 0; element < lutArray.depth; element++)
            {
                for (int mip = 0; mip < mipCount; mip++)
                {
                    Graphics.CopyTexture(lutArray, element, mip, existingLutArray, element, mip);
                }
            }
            lutArray = existingLutArray;
            EditorUtility.SetDirty(lutArray);
        }
        else
        {
            AssetDatabase.CreateAsset(lutArray, lutArrayFilename);
        }

        AssetDatabase.SaveAssets();

        // Apply references to materials
        foreach (Material mat in materials)
        {
            mat.SetTexture("_GoboTex", texArray);
            mat.SetTexture("_GoboLUT", lutArray);
        }

        AssetDatabase.SaveAssets();
    }
}

#endif