using System.IO;
using System.Linq;

#if UNITY_EDITOR
using UnityEditor;
#endif
using UnityEngine;
using UnityEngine.SceneManagement;

#if UNITY_EDITOR
[System.Serializable]
public class GoboArray
{
    public string name = "gobo";
    public Texture[] gobos;
}
#endif

public class LUTBeamManager : MonoBehaviour
{
#if UNITY_EDITOR

    // Forces unity to not copy the last element when adding a new one
    private void OnValidate()
    {
        if (goboArray.Length > lastGoboArraySize && lastGoboArraySize != -1)
        {
            goboArray[goboArray.Length - 1].name = "New Gobo Array";
            goboArray[goboArray.Length - 1].gobos = null;
        }

        lastGoboArraySize = goboArray.Length;
    }

    [SerializeField, HideInInspector]
    private int lastGoboArraySize = -1;

    public GoboArray[] goboArray;
    public TextureFormat format = TextureFormat.BC4;

    public string AutoGenerateDirectory = "Assets/LUTBeam/Autogenerated";

    public int LUTResolution = 1024;
    public int GoboResolution = 512;

    [ContextMenu("Generate Texture Array")]
    public void _GenerateTextureArray()
    {
        for (int i = 0; i < goboArray.Length; i++)
        {
            Texture[] gobos = goboArray[i].gobos;
            string prefix = goboArray[i].name;

            if (gobos.Length == 0)
                continue;

            Texture2D[] goboTextures = new Texture2D[gobos.Length];
            Texture2D[] lutTextures = new Texture2D[gobos.Length];

            Material material = new Material(Shader.Find("LUTBeam/GoboLookupGenerator"));

            for (int q = 0; q < gobos.Length; q++)
            {
                if (!(gobos[q] is Texture2D))
                    continue;

                Texture2D Gobo = gobos[q] as Texture2D;

                if (!Gobo)
                    return;

                RenderTexture tempRTLut = new RenderTexture(LUTResolution, LUTResolution, 32, RenderTextureFormat.ARGBFloat);
                RenderTexture tempRTGobo = new RenderTexture(GoboResolution, GoboResolution, 32, RenderTextureFormat.ARGBFloat);

                material.SetTexture("_MainTex", Gobo);
                // Also allow the shader to process the gobo itself, if desired.
                Shader.SetGlobalFloat("_EnableBake_Gobo", 1);
                Graphics.Blit(null, tempRTGobo, material);
                Shader.SetGlobalFloat("_EnableBake_Gobo", 0);

                RenderTexture.active = tempRTGobo;
                Texture2D texGobo = new Texture2D(GoboResolution, GoboResolution, TextureFormat.RGBAFloat, false);
                texGobo.ReadPixels(new Rect(0, 0, GoboResolution, GoboResolution), 0, 0);
                texGobo.Apply();
                RenderTexture.active = null;

                goboTextures[q] = texGobo;

                material.SetTexture("_MainTex", texGobo);

                // Enable supersampling mode of the baker because it makes it look way better!
                Shader.SetGlobalFloat("_EnableBake_Supersample", 1);
                Graphics.Blit(null, tempRTLut, material);
                Shader.SetGlobalFloat("_EnableBake_Supersample", 0);

                RenderTexture.active = tempRTLut;
                Texture2D texLut = new Texture2D(LUTResolution, LUTResolution, TextureFormat.RGBAFloat, false);
                texLut.ReadPixels(new Rect(0, 0, LUTResolution, LUTResolution), 0, 0);
                texLut.Apply();
                RenderTexture.active = null;


                // Convert linear to srgb in the texture
                for (int x = 0; x < GoboResolution; x++)
                {
                    for (int y = 0; y < GoboResolution; y++)
                    {
                        Color c = texGobo.GetPixel(x, y);
                        c.r = Mathf.LinearToGammaSpace(c.r);
                        c.g = Mathf.LinearToGammaSpace(c.g);
                        c.b = Mathf.LinearToGammaSpace(c.b);
                        texGobo.SetPixel(x, y, c);
                    }
                }
                texGobo.Apply();

                // Convert linear to srgb in the texture
                for (int x = 0; x < LUTResolution; x++)
                {
                    for (int y = 0; y < LUTResolution; y++)
                    {
                        Color c = texLut.GetPixel(x, y);
                        c.r = Mathf.LinearToGammaSpace(c.r);
                        c.g = Mathf.LinearToGammaSpace(c.g);
                        c.b = Mathf.LinearToGammaSpace(c.b);
                        texLut.SetPixel(x, y, c);
                    }
                }
                texLut.Apply();

                lutTextures[q] = texLut;
            }

            Scene scene = SceneManager.GetActiveScene();

            if (!Directory.Exists(AutoGenerateDirectory))
                Directory.CreateDirectory(AutoGenerateDirectory);

            Texture2DArray texArray = new Texture2DArray(GoboResolution, GoboResolution, gobos.Length, format, false, false);
            Texture2DArray lutArray = new Texture2DArray(LUTResolution, LUTResolution, gobos.Length, format, false, false);

            int mip = 0;
            for (int j = 0; j < gobos.Length; j++)
            {
                EditorUtility.CompressTexture(goboTextures[j], format, TextureCompressionQuality.Best);
                Graphics.CopyTexture(goboTextures[j], 0, mip, texArray, j, mip);

                EditorUtility.CompressTexture(lutTextures[j], format, TextureCompressionQuality.Best);
                Graphics.CopyTexture(lutTextures[j], 0, mip, lutArray, j, mip);
            }


            string texArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} - Gobo Textures.asset";
            string lutArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} - LUT Textures.asset";
            if (!string.IsNullOrWhiteSpace(prefix))
            {
                texArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} {prefix} - Gobo Textures.asset";
                lutArrayFilePath = $"{AutoGenerateDirectory}/{scene.name} {prefix} - LUT Textures.asset";
            }


            Texture2DArray existingTexArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(texArrayFilePath);
            if (existingTexArray)
            {
                EditorUtility.CopySerialized(texArray, existingTexArray);
                EditorUtility.SetDirty(existingTexArray);
                texArray = existingTexArray;
            }
            else
            {
                AssetDatabase.CreateAsset(texArray, texArrayFilePath);
            }

            Texture2DArray existingLutArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(lutArrayFilePath);
            if (existingLutArray)
            {
                EditorUtility.CopySerialized(lutArray, existingLutArray);
                EditorUtility.SetDirty(existingLutArray);
                lutArray = existingLutArray;
            }
            else
            {
                AssetDatabase.CreateAsset(lutArray, lutArrayFilePath);
            }

            AssetDatabase.SaveAssets();

            EditorGUIUtility.PingObject(lutArray);

        }
    }
#endif

}