#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;

public class LUTBeamMaterialManager : MonoBehaviour
{
    public Texture[] gobos;
    public Material[] materials;
    public string AutoGenerateDirectory = "Assets/LUTBeam/Autogenerated";

    public string prefix = "";

    public int LUTResolution = 1024;
    public int GoboResolution = 512;

    [ContextMenu("Generate Materials")]
    public void _GenerateMaterials()
    {
        Texture2D[] goboTextures = new Texture2D[gobos.Length];
        Texture2D[] lutTextures = new Texture2D[gobos.Length];

        Material material = new Material(Shader.Find("LUTBeam/GoboLookupGenerator"));

        for (int q = 0; q < gobos.Length; q++)
        {
            if (!(gobos[q] is Texture2D))
                continue;

            Texture2D Gobo = gobos[q] as Texture2D;

            if (!Gobo)
                return;

            RenderTexture tempRT = new RenderTexture(LUTResolution, LUTResolution, 32, RenderTextureFormat.ARGBFloat);

            material.SetTexture("_MainTex", Gobo);
            material.SetFloat("_Fast", 0);

            Graphics.Blit(null, tempRT, material);

            RenderTexture.active = tempRT;
            Texture2D tex = new Texture2D(LUTResolution, LUTResolution, TextureFormat.RGBAFloat, false);
            tex.ReadPixels(new Rect(0, 0, LUTResolution, LUTResolution), 0, 0);
            tex.Apply();
            RenderTexture.active = null;

            // Convert linear to srgb in the texture
            for (int x = 0; x < LUTResolution; x++)
            {
                for (int y = 0; y < LUTResolution; y++)
                {
                    Color c = tex.GetPixel(x, y);
                    c.r = Mathf.LinearToGammaSpace(c.r);
                    c.g = Mathf.LinearToGammaSpace(c.g);
                    c.b = Mathf.LinearToGammaSpace(c.b);
                    tex.SetPixel(x, y, c);
                }
            }
            tex.Apply();

            goboTextures[q] = Gobo;
            lutTextures[q] = tex;
        }
        TextureFormat format = TextureFormat.BC4;

        Texture2DArray texArray = null;
        Texture2DArray lutArray = null;

        Scene scene = SceneManager.GetActiveScene();

        if (!Directory.Exists(AutoGenerateDirectory))
            Directory.CreateDirectory(AutoGenerateDirectory);

        string texArrayFilename = $"{AutoGenerateDirectory}/{scene.name} {prefix} - Gobo Textures.asset";
        string lutArrayFilename = $"{AutoGenerateDirectory}/{scene.name} {prefix} - LUT Textures.asset";

        Texture2DArray existingTexArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(texArrayFilename);
        if (existingTexArray != null && 
            existingTexArray.width == texArray.width && 
            existingTexArray.height == texArray.height && 
            existingTexArray.depth == texArray.depth && 
            existingTexArray.format == texArray.format)
        {
            texArray = existingTexArray;
            EditorUtility.SetDirty(texArray);
        }
        else
        {
            texArray = new Texture2DArray(GoboResolution, GoboResolution, gobos.Length, format, false, false);
            AssetDatabase.CreateAsset(texArray, texArrayFilename);
        }

        Texture2DArray existingLutArray = AssetDatabase.LoadAssetAtPath<Texture2DArray>(lutArrayFilename);
        if (existingLutArray != null && 
            existingLutArray.width == lutArray.width &&
            existingLutArray.height == lutArray.height && 
            existingLutArray.depth == lutArray.depth && 
            existingLutArray.format == lutArray.format)
        {
            lutArray = existingLutArray;
            EditorUtility.SetDirty(lutArray);
        }
        else
        {
            lutArray = new Texture2DArray(LUTResolution, LUTResolution, gobos.Length, format, false, false);
            AssetDatabase.CreateAsset(lutArray, lutArrayFilename);
        }

        for (int i = 0; i < gobos.Length; i++)
        {
            RenderTexture goboTempRT = new RenderTexture(GoboResolution, GoboResolution, 0, RenderTextureFormat.ARGBFloat);
            Texture2D goboTex = new Texture2D(GoboResolution, GoboResolution, TextureFormat.RGBAFloat, false, false);
            Graphics.Blit(goboTextures[i], goboTempRT);
            goboTex.ReadPixels(new Rect(0, 0, GoboResolution, GoboResolution), 0, 0);
            goboTex.Apply(true);
            
            EditorUtility.CompressTexture(goboTex, format, TextureCompressionQuality.Best);

            for (int mip = 0; mip < goboTex.mipmapCount; mip++)
            {
                Graphics.CopyTexture(goboTex, 0, mip, texArray, i, mip);
            }

            RenderTexture lutTempRT = new RenderTexture(LUTResolution, LUTResolution, 0, RenderTextureFormat.ARGBFloat);
            Texture2D lutTex = new Texture2D(LUTResolution, LUTResolution, TextureFormat.RGBAFloat, false, false);
            Graphics.Blit(lutTextures[i], lutTempRT);
            lutTex.ReadPixels(new Rect(0, 0, LUTResolution, LUTResolution), 0, 0);
            lutTex.Apply(true);
            EditorUtility.CompressTexture(lutTex, format, TextureCompressionQuality.Best);

            for (int mip = 0; mip < lutTex.mipmapCount; mip++)
            {
                Graphics.CopyTexture(lutTex, 0, mip, lutArray, i, mip);
            }
        }
        AssetDatabase.SaveAssets();

        // Apply references to materials
        foreach (Material mat in materials)
        {
            mat.SetTexture("_GoboTex", texArray);
            mat.SetTexture("_GoboLUT", lutArray);
        }

        AssetDatabase.SaveAssets();
    }
}

#endif